[workspace]
resolver = "3"
members = ["vulpes", "main"]

[workspace.dependencies]
rustyline = "14.0"
reqwest = "0.12.22"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.46.1", features = ["full"] }
vulpes = { path = "../vulpes" }
