[package]
name = "vulpes"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
async-trait.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
